apps/coin_flip_betting_game_interface/lib/coin_flip_betting_game_interface_web/router.ex
defmodule CoinFlipBettingGameInterfaceWeb.Router do
  use CoinFlipBettingGameInterfaceWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", CoinFlipBettingGameInterfaceWeb do
    pipe_through(:browser)

    get("/", TableSessionController, :index)

    resources("/table-sessions", TableSessionController, only: [:index, :show, :create]) do
      post("/flip", TableSessionController, :flip)
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", CoinFlipBettingGameInterfaceWeb do
  #   pipe_through :api
  # end
end

apps/coin_flip_betting_game_interface/lib/coin_flip_betting_game_interface/application.ex
defmodule CoinFlipBettingGameInterface.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the endpoint when the application starts
      CoinFlipBettingGameInterfaceWeb.Endpoint
      # Starts a worker by calling: CoinFlipBettingGameInterface.Worker.start_link(arg)
      # {CoinFlipBettingGameInterface.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: CoinFlipBettingGameInterface.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    CoinFlipBettingGameInterfaceWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

apps/coin_flip_betting_game_interface/lib/coin_flip_betting_game_interface/random_name.ex
defmodule CoinFlipBettingGameInterface.RandomName do
  def pick() do
    "#{adjective()}-#{noun()}"
  end

  def adjective() do
    [
      "autumn",
      "hidden",
      "bitter",
      "misty",
      "silent",
      "empty",
      "dry",
      "dark",
      "summer",
      "icy",
      "delicate",
      "quiet",
      "white",
      "cool",
      "spring",
      "winter",
      "patient",
      "twilight",
      "dawn",
      "crimson",
      "wispy",
      "weathered",
      "blue",
      "billowing",
      "broken",
      "cold",
      "damp",
      "falling",
      "frosty",
      "green",
      "long",
      "late",
      "lingering",
      "bold",
      "little",
      "morning",
      "muddy",
      "old",
      "red",
      "rough",
      "still",
      "small",
      "sparkling",
      "throbbing",
      "shy",
      "wandering",
      "withered",
      "wild",
      "black",
      "young",
      "holy",
      "solitary",
      "fragrant",
      "aged",
      "snowy",
      "proud",
      "floral",
      "restless",
      "divine",
      "polished",
      "ancient",
      "purple",
      "lively",
      "nameless"
    ]
    |> Enum.random()
  end

  defp noun() do
    [
      "waterfall",
      "river",
      "breeze",
      "moon",
      "rain",
      "wind",
      "sea",
      "morning",
      "snow",
      "lake",
      "sunset",
      "pine",
      "shadow",
      "leaf",
      "dawn",
      "glitter",
      "forest",
      "hill",
      "cloud",
      "meadow",
      "sun",
      "glade",
      "bird",
      "brook",
      "butterfly",
      "bush",
      "dew",
      "dust",
      "field",
      "fire",
      "flower",
      "firefly",
      "feather",
      "grass",
      "haze",
      "mountain",
      "night",
      "pond",
      "darkness",
      "snowflake",
      "silence",
      "sound",
      "sky",
      "shape",
      "surf",
      "thunder",
      "violet",
      "water",
      "wildflower",
      "wave",
      "water",
      "resonance",
      "sun",
      "wood",
      "dream",
      "cherry",
      "tree",
      "fog",
      "frost",
      "voice",
      "paper",
      "frog",
      "smoke",
      "star"
    ]
    |> Enum.random()
  end
end

apps/coin_flip_betting_game_interface/lib/coin_flip_betting_game_interface_web/controllers/page_controller.ex
defmodule CoinFlipBettingGameInterfaceWeb.PageController do
  use CoinFlipBettingGameInterfaceWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

apps/coin_flip_betting_game_interface/lib/coin_flip_betting_game_interface_web/controllers/table_session_controller.ex
defmodule CoinFlipBettingGameInterfaceWeb.TableSessionController do
  use CoinFlipBettingGameInterfaceWeb, :controller

  def index(conn, _params) do
    table_sessions = CoinFlipBettingGameInterface.get_table_sessions()
    render(conn, "index.html", table_sessions: table_sessions)
  end

  def show(conn, %{"id" => id}) do
    table = CoinFlipBettingGameInterface.get_table(id)
    render(conn, "show.html", table_session: table)
  end

  def flip(conn, %{"table_session_id" => id}) do
    CoinFlipBettingGameInterface.flip_coin_on_table(id)
    redirect(conn, to: Routes.table_session_path(conn, :show, id))
  end

  def create(conn, _params) do
    CoinFlipBettingGameInterface.create_table_session()
    table_sessions = CoinFlipBettingGameInterface.get_table_sessions()
    render(conn, "index.html", table_sessions: table_sessions)
  end
end

apps/coin_flip_betting_game_interface/lib/coin_flip_betting_game_interface_web/views/error_view.ex
defmodule CoinFlipBettingGameInterfaceWeb.ErrorView do
  use CoinFlipBettingGameInterfaceWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/coin_flip_betting_game_interface/lib/coin_flip_betting_game_interface_web/views/layout_view.ex
defmodule CoinFlipBettingGameInterfaceWeb.LayoutView do
  use CoinFlipBettingGameInterfaceWeb, :view
end

apps/coin_flip_betting_game_interface/lib/coin_flip_betting_game_interface_web/views/page_view.ex
defmodule CoinFlipBettingGameInterfaceWeb.PageView do
  use CoinFlipBettingGameInterfaceWeb, :view
end

apps/coin_flip_betting_game_interface/lib/coin_flip_betting_game_interface_web/views/table_session_view.ex
defmodule CoinFlipBettingGameInterfaceWeb.TableSessionView do
  use CoinFlipBettingGameInterfaceWeb, :view

  def table_name(table), do: table.name

  def coin_value(%{coin: %{value: nil}}), do: "Not flipped yet"
  def coin_value(%{coin: %{value: value}}), do: value |> to_string() |> String.capitalize()
end

apps/coin_flip_betting_game_interface/lib/coin_flip_betting_game_interface_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>CoinFlipBettingGameInterface · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

apps/coin_flip_betting_game_interface/lib/coin_flip_betting_game_interface_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>does not compromise speed or maintainability.</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
    </ul>
  </article>
</section>

apps/coin_flip_betting_game_interface/lib/coin_flip_betting_game_interface_web/templates/table_session/index.html.eex
<h1>Coin Flip Betting Game</h1>

<table>
  <%= for table_session <- @table_sessions do %>
    <tr>
      <td><%= link(table_session, to: Routes.table_session_path(@conn, :show, table_session)) %>
    </tr>
  <% end %>
</table>

<%= button("New table", to: Routes.table_session_path(@conn, :create)) %>

apps/coin_flip_betting_game_interface/lib/coin_flip_betting_game_interface_web/templates/table_session/show.html.eex
<h1>Coin Flip Betting Game - <%= table_name(@table_session) %></h1>

<p><%= coin_value(@table_session) %></p>

<%= button("Flip", to: Routes.table_session_table_session_path(@conn, :flip, table_name(@table_session)), method: "post") %>